"""empty message

Revision ID: 167567cbee65
Revises: efcc8007ecba
Create Date: 2021-12-01 12:00:33.343365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167567cbee65'
down_revision = 'efcc8007ecba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.Column('player', sa.String(length=100), nullable=True),
    sa.Column('match', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
